version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - rabbitmq_net
  billing-service:
    build:
      context: ./billing-service
      dockerfile: Dockerfile
    ports:
      - 5002:5002
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq_net
  inventory-service:
    build:
      context: ./inventory-service
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq_net  
  shipping-service:
    build:
      context: ./shipping-service
      dockerfile: Dockerfile
    ports:
      - 5007:5007
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq_net
  users-service:
    build:
      context: ./users-service
      dockerfile: Dockerfile
    ports:
      - 5003:5003
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq_net
  data-service:
    build:
      context: ./data-service
      dockerfile: Dockerfile
    ports:
      - 5009:5009
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq_net
  webhook-service:
    build:
      context: ./webhook-service
      dockerfile: Dockerfile
    ports:
      - 5001:5001
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq_net

networks:
  rabbitmq_net:
    driver: bridge

volumes:
  rabbitmq_data: