version: '3'
services:
  billing-service:
    build:
      context: ./billing-service
      dockerfile: Dockerfile
    ports:
      - 5006:5002
  inventory-service:
    build:
      context: ./inventory-service
      dockerfile: Dockerfile
    ports:
      - 5001:5000
  shipping-service:
    build:
      context: ./shipping-service
      dockerfile: Dockerfile
    ports:
      - 5009:5007
  users-service:
    build:
      context: ./users-service
      dockerfile: Dockerfile
    ports:
      - 5003:5003
