apiVersion: v1
kind: Pod
metadata:
  name: redis-pod-20739
  labels:
    app: redis
spec:
  containers:
    - name: redis-container
      image: redis:latest
      ports:
        - containerPort: 20739
