apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment-20739
  labels:
    app: redis
spec:
  replicas: 9  
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis-container
          image: redis:latest
          ports:
            - containerPort: 20739
